version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: ./api
        volumes:
            - /app/node_modules
            - ./api:/app
        environment:
            - NODE_ENV=dev
            - PORT=5000
            - INSTANCE=server1
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        links:
            - api
        ports:
            - "80:80"
